version: "3"

services:
  petstorepetservice:
    build:
      context: ./petstore/petstorepetservice
      dockerfile: Dockerfile
    image: petstoreacrdemo.azurecr.io/petstorepetservice
    environment:
      - PETSTOREPETSERVICE_SERVER_PORT=8081
    ports:
      - 8081:8081
  petstoreproductservice:
    build:
      context: ./petstore/petstoreproductservice
      dockerfile: Dockerfile
    image: petstoreacrdemo.azurecr.io/petstoreproductservice
    environment:
      - PETSTOREPRODUCTSERVICE_SERVER_PORT=8082
    ports:
      - 8082:8082
  petstoreorderservice:
    build:
      context: ./petstore/petstoreorderservice
      dockerfile: Dockerfile
    image: petstoreacrdemo.azurecr.io/petstoreorderservice
    environment:
      - PETSTOREORDERSERVICE_SERVER_PORT=8083
    ports:
      - 8083:8083
  petstoreapp:
    build:
      context: ./petstore/petstoreapp
      dockerfile: Dockerfile
    image: petstoreacrdemo.azurecr.io/petstoreapp
    environment:
      - PETSTOREAPP_SERVER_PORT=8080
      - PETSTOREPETSERVICE_URL=http://petstorepetservice:8081
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
      - PETSTOREORDERSERVICE_URL=http://petstoreorderservice:8083
    ports:
      - 8080:8080
